apiVersion: v1
kind: Secret
metadata:
  name: agentflow-secret
  namespace: agentflow
type: Opaque
stringData:
  # 请修改为实际部署时使用的密码
  AUTH_PASSWORD: admin
  # 请修改为至少32字符的随机字符串
  AUTH_API_KEY_SECRET: your_very_secure_api_key_secret_at_least_32_characters_long
