apiVersion: v1
kind: Service
metadata:
  name: agentflow-master
  namespace: agentflow
  labels:
    app: agentflow-master
spec:
  selector:
    app: agentflow-master

  ports:
  - port: 6767
    targetPort: 6767
    name: http
  - port: 8849
    targetPort: 8849
    name: websocket

  type: ClusterIP
